version: '3.8'
services:
  postgresql:
    image: "bitnami/postgresql:latest"
    volumes:
      - postgresql-data:/bitnami/postgresql
    ports:
      - "5446:5432"
    environment:
      - POSTGRESQL_DATABASE=al-test-3
      - POSTGRESQL_USERNAME=superuser
      - POSTGRESQL_PASSWORD=superuser
      - POSTGRESQL_POSTGRES_PASSWORD=superuser
  al_test:
    build: ./
    ports:
      - 5001:80
    depends_on:
      - postgresql
    command: ["./wait-for-it.sh", "postgresql:5432", "--", "python", "scripts.py"]

volumes:
  postgresql-data:
   